### ISSUE TITLE
Decimals.jl support

### ISSUE THREAD

**Issue by johnzl-777** [awslabs/Braket.jl#33]
**Describe the feature you'd like**
The current Braket IR uses `Dec128` from `DecFP` to represent the Decimal type but this relies on an external Intel library. It would be nice if `Decimals.jl` support could be added as a Julia-native option for the Decimal type.

**How would this feature be used? Please describe.**
There are plans for the [Bloqade.jl](https://github.com/QuEraComputing/Bloqade.jl) schema to use `Decimals.jl`. If the Braket IR supported `Decimals.jl` it would make future IR conversions much easier 😃 

Credit to @Roger-luo and @weinbe58 for the idea

**Comment by kshyatt-aws** [comment]
The problem for us is that Decimals.jl seems pretty abandoned (last tagged version in 2020) and the `Decimal` type doesn't support hashing, for example. Is the reliance on an Intel library the main blocker for you? Would it be enough to modify `Braket.jl` to allow constructing the higher-level constructs using `Decimal` even if internally they use `Dec128`?

**Comment by weinbe58** [comment]
No, its not a blocker for us, It would be nice to have a pure Julia implementation to support the most platforms. 

I think in the Long term a redesign of the IR will hopefully make this need for Dec128 obsolete, more details to come hopefully.
